[2024-12-25T23:27:06.811+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-25T23:27:05.943508+00:00 [queued]>
[2024-12-25T23:27:06.815+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-25T23:27:05.943508+00:00 [queued]>
[2024-12-25T23:27:06.815+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-25T23:27:06.815+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2024-12-25T23:27:06.815+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-25T23:27:06.819+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): run_currency_exchange_etl> on 2024-12-25 23:27:05.943508+00:00
[2024-12-25T23:27:06.821+0000] {standard_task_runner.py:55} INFO - Started process 51 to run task
[2024-12-25T23:27:06.823+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'run_currency_exchange_etl', 'manual__2024-12-25T23:27:05.943508+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmpahbnofej']
[2024-12-25T23:27:06.824+0000] {standard_task_runner.py:83} INFO - Job 12: Subtask run_currency_exchange_etl
[2024-12-25T23:27:06.832+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-25T23:27:06.854+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-25T23:27:05.943508+00:00 [running]> on host 850d5b62fd10
[2024-12-25T23:27:06.879+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_pipeline
AIRFLOW_CTX_TASK_ID=run_currency_exchange_etl
AIRFLOW_CTX_EXECUTION_DATE=2024-12-25T23:27:05.943508+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-25T23:27:05.943508+00:00
[2024-12-25T23:27:06.879+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-25T23:27:06.880+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/currency_exchange_etl.py']
[2024-12-25T23:27:06.884+0000] {subprocess.py:86} INFO - Output:
[2024-12-25T23:27:07.151+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-12-25T23:27:07.152+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/currency_exchange_etl.py", line 129, in <module>
[2024-12-25T23:27:07.152+0000] {subprocess.py:93} INFO -     main()
[2024-12-25T23:27:07.155+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/currency_exchange_etl.py", line 110, in main
[2024-12-25T23:27:07.158+0000] {subprocess.py:93} INFO -     date = datetime.strptime(data['Realtime Currency Exchange Rate']["6. Last Refreshed"], '%Y-%m-%d %H:%M:%S').date()
[2024-12-25T23:27:07.159+0000] {subprocess.py:93} INFO - KeyError: 'Realtime Currency Exchange Rate'
[2024-12-25T23:27:07.162+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-25T23:27:07.168+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-25T23:27:07.170+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=etl_pipeline, task_id=run_currency_exchange_etl, execution_date=20241225T232705, start_date=20241225T232706, end_date=20241225T232707
[2024-12-25T23:27:07.174+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 12 for task run_currency_exchange_etl (Bash command failed. The command returned a non-zero exit code 1.; 51)
[2024-12-25T23:27:07.186+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-25T23:27:07.195+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
