[2024-12-25T23:32:07.862+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-25T23:27:05.943508+00:00 [queued]>
[2024-12-25T23:32:07.866+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-25T23:27:05.943508+00:00 [queued]>
[2024-12-25T23:32:07.866+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-25T23:32:07.866+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2024-12-25T23:32:07.866+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-25T23:32:07.871+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): run_currency_exchange_etl> on 2024-12-25 23:27:05.943508+00:00
[2024-12-25T23:32:07.873+0000] {standard_task_runner.py:55} INFO - Started process 54 to run task
[2024-12-25T23:32:07.874+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'etl_pipeline', 'run_currency_exchange_etl', 'manual__2024-12-25T23:27:05.943508+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/currency_exchange_dag.py', '--cfg-path', '/tmp/tmphaeu30yd']
[2024-12-25T23:32:07.874+0000] {standard_task_runner.py:83} INFO - Job 13: Subtask run_currency_exchange_etl
[2024-12-25T23:32:07.883+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.9/site-packages/airflow/settings.py:249: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2024-12-25T23:32:07.915+0000] {task_command.py:388} INFO - Running <TaskInstance: etl_pipeline.run_currency_exchange_etl manual__2024-12-25T23:27:05.943508+00:00 [running]> on host 850d5b62fd10
[2024-12-25T23:32:07.947+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=etl_pipeline
AIRFLOW_CTX_TASK_ID=run_currency_exchange_etl
AIRFLOW_CTX_EXECUTION_DATE=2024-12-25T23:27:05.943508+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-25T23:27:05.943508+00:00
[2024-12-25T23:32:07.948+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-25T23:32:07.948+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python /opt/airflow/dags/currency_exchange_etl.py']
[2024-12-25T23:32:07.953+0000] {subprocess.py:86} INFO - Output:
[2024-12-25T23:32:08.286+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2024-12-25T23:32:08.287+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/currency_exchange_etl.py", line 129, in <module>
[2024-12-25T23:32:08.287+0000] {subprocess.py:93} INFO -     main()
[2024-12-25T23:32:08.287+0000] {subprocess.py:93} INFO -   File "/opt/airflow/dags/currency_exchange_etl.py", line 110, in main
[2024-12-25T23:32:08.287+0000] {subprocess.py:93} INFO -     date = datetime.strptime(data['Realtime Currency Exchange Rate']["6. Last Refreshed"], '%Y-%m-%d %H:%M:%S').date()
[2024-12-25T23:32:08.287+0000] {subprocess.py:93} INFO - KeyError: 'Realtime Currency Exchange Rate'
[2024-12-25T23:32:08.296+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-25T23:32:08.303+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-25T23:32:08.305+0000] {taskinstance.py:1318} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=run_currency_exchange_etl, execution_date=20241225T232705, start_date=20241225T233207, end_date=20241225T233208
[2024-12-25T23:32:08.310+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 13 for task run_currency_exchange_etl (Bash command failed. The command returned a non-zero exit code 1.; 54)
[2024-12-25T23:32:08.316+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-25T23:32:08.325+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
